// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        //classpath 'com.android.tools.build:gradle:3.1.0'
        //classpath 'com.novoda:bintray-release:0.8.1'
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        maven { url("https://oss.sonatype.org/content/repositories/snapshots/") }
        mavenCentral()
    }
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
